### ISSUE TITLE
Create action to zoom

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-roi#52]
A new function returned by the `useRoiActions` hook

```js
const { zoom } = useRoiActions();

function onZoom() {
  zoom({ factor: 1.2 }); // Zooms towards the center of the coordinate system
}
```

**Comment by Sebastien-Ahkrin** [comment]
I'm not really sure that we have to export "zoom" on useRoiActions. 
I think, on zoom i will have to get access to the roiContainerRef, who's in a new context. For that, I will have to be in "RoiContainer" and not on only on "RoiProvider", and that, only for 1 action. 

It can be a little "strange" for the user to have access to many action by useRoiActions, and can use everything on RoiProvider, but having some only useful when you'r inside "RoiContainer". 

I'm not sure if it understandable, but i would suggest to create a new hook (like useContainerActions) instead of using the useRoiActions.

Are you ok with that @stropitek ?

**Comment by stropitek** [comment]
Just make sure that the hook does not unnecessarily updates.
